services:
  - type: web
    name: campusflow-backend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: JWT_RESET_SECRET
        sync: false
      - key: JWT_RESET_EXPIRES_IN
        value: 1h
      - key: FRONTEND_URL
        sync: false
      - key: FRONTEND_RESET_PASSWORD_URL
        sync: false
      - key: STUDENT_FRONTEND_URL
        sync: false
      - key: STAFF_FRONTEND_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_FROM_ADDRESS
        sync: false
      - key: EMAIL_FROM_NAME
        value: CampusFlow
      - key: WEB_PUSH_PUBLIC_KEY
        sync: false
      - key: WEB_PUSH_PRIVATE_KEY
        sync: false
      - key: WEB_PUSH_SUBJECT
        sync: false
      - key: BCRYPT_ROUNDS
        value: "12"
